update with new staff
cartabinaria/isi-computational-statistics pull request #1
Opened 2024-11-20 11:26 UTC by Diebbo

2024-11-20 13:56 UTC, ali-benny requested changes
@Diebbo Thanks for the resources, but the `slides` should follow the format `index-name.extension`, where "index" is two-digit number and "name" is a kebab-case description/title

2024-11-25 14:25 UTC, ali-benny reviewed
It seems that the filenames are properly arranged. The only concern is whether the booklets are under a free license; otherwise, I’m afraid we won’t be able to include them. Does that sound right @samuelemusiani ?

2024-11-25 14:30 UTC, Diebbo commented
They were all given by the professor on the course's virtuale page.

2024-11-25 14:31 UTC, ali-benny approved these changes

2024-11-25 14:32 UTC, merged